DROP DATABASE IF EXISTS project CASCADE;
CREATE DATABASE IF NOT EXISTS pro ject;
SET DATABASE = project;

CREATE TABLE IF NOT EXISTS users(
    id SERIAL NOT NULL PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE,
    username VARCHAR NOT NULL UNIQUE,
);